-- For MySQL
--
-- BLADE Analytics schema (v3 layout).
--
-- Optimizations vs. earlier schema:
--   * `application.id` widened to BIGINT to match the 64-bit producer-random
--     identity. `collisions` column dropped (collision risk is now ~10^-11).
--   * `event.name` and `attribute.name` normalized to short FK lookups
--     (`event_type`, `attribute_name`) — saves ~50 bytes per row on the
--     hottest tables.
--   * `attribute.value` is now VARCHAR(1024) rather than TEXT so most
--     rows stay in-page in InnoDB instead of being stored off-page.
--   * `event` index `(event_type_id, created)` replaces the single-column
--     `(name)` index — better-shaped for typical "events of type T in range"
--     queries.
--
-- Partitioning is documented at the bottom; enable with ALTER TABLE when
-- the retention policy is settled.

DROP TABLE IF EXISTS attribute;
DROP TABLE IF EXISTS attribute_name;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS event_type;
DROP TABLE IF EXISTS session_key;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS application;

-- this table tracks application instances, unique deployments in time
CREATE TABLE application(
   -- random 64-bit value generated by the producer at servlet init time,
   -- captured in the analytics DB on first inbound message for this id
   id BIGINT NOT NULL,
   CONSTRAINT application_pk PRIMARY KEY(id),

   -- application name, like 'transfer' (without version number)
   name VARCHAR(32) NOT NULL,

   -- application version, like '1.0.1'
   version VARCHAR(16) DEFAULT NULL,

   -- hostname of the machine, like engine1.replicated.vorpal.org
   host VARCHAR(128) DEFAULT NULL,

   -- weblogic cluster domain, like 'replicated'; not related to DNS
   domain VARCHAR(64) DEFAULT NULL,

   -- weblogic server name, like 'engine1'; not related to hostname
   server VARCHAR(64) DEFAULT NULL,

   -- instant the application started
   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

   -- instant the application stopped (NULL while running)
   destroyed TIMESTAMP NULL DEFAULT NULL,

   -- additional user-defined data, like hardware specs (JSON format)
   comments TEXT NULL
);

CREATE TABLE session(
    -- producer-set snowflake id (see SnowflakeId.java); not auto-increment
    id BIGINT NOT NULL,
    CONSTRAINT session_pk PRIMARY KEY(id),

    -- the application that created this session
    application_id BIGINT NOT NULL,
    CONSTRAINT session_fk1 FOREIGN KEY (application_id)
    REFERENCES application(id) ON DELETE CASCADE,

    -- instant it was first generated
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_session_created (created),
    INDEX idx_session_app_created (application_id, created),

    -- instant it was destroyed (NULL while active)
    destroyed TIMESTAMP NULL DEFAULT NULL
);

-- index keys referencing a session (selectors, e.g. 'Cisco-Gucid' or 'caller')
CREATE TABLE session_key(
    session_id BIGINT NOT NULL,
      CONSTRAINT session_key_fk1 FOREIGN KEY (session_id)
      REFERENCES session(id) ON DELETE CASCADE,
    name VARCHAR(64) NOT NULL,
    value VARCHAR(128) NOT NULL,

      CONSTRAINT session_key_pk
      PRIMARY KEY(session_id, name, value),

    INDEX idx_session_key_lookup (name, value)
);

-- normalized event-name lookup; populated lazily by the consumer on first sighting
CREATE TABLE event_type(
   id SMALLINT NOT NULL AUTO_INCREMENT,
   CONSTRAINT event_type_pk PRIMARY KEY(id),
   name VARCHAR(64) NOT NULL,
   CONSTRAINT event_type_uk UNIQUE (name)
);

-- events associated with a session (and/or application for sessionless events)
CREATE TABLE event(

   -- auto-incremented primary key
   id BIGINT NOT NULL AUTO_INCREMENT,
     CONSTRAINT event_pk PRIMARY KEY(id),

   -- all events originate from an application instance
   application_id BIGINT NOT NULL,
     CONSTRAINT event_fk1
     FOREIGN KEY (application_id)
     REFERENCES application(id) ON DELETE CASCADE,

   -- may be null for sessionless events like startup & shutdown
   session_id BIGINT NULL,
     CONSTRAINT event_fk2
     FOREIGN KEY (session_id)
     REFERENCES session(id) ON DELETE CASCADE,

   -- type of event (normalized FK to event_type)
   event_type_id SMALLINT NOT NULL,
     CONSTRAINT event_fk3
     FOREIGN KEY (event_type_id)
     REFERENCES event_type(id),

   -- timestamp of event
   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

   -- indexes for common queries
   INDEX idx_event_session (session_id, created),
   INDEX idx_event_type_created (event_type_id, created),
   INDEX idx_event_created (created)
);

-- normalized attribute-name lookup; populated lazily by the consumer
CREATE TABLE attribute_name(
   id SMALLINT NOT NULL AUTO_INCREMENT,
   CONSTRAINT attribute_name_pk PRIMARY KEY(id),
   name VARCHAR(64) NOT NULL,
   CONSTRAINT attribute_name_uk UNIQUE (name)
);

-- key/value attributes attached to an event
CREATE TABLE attribute(
   event_id BIGINT NOT NULL,
     CONSTRAINT attribute_fk1
     FOREIGN KEY (event_id)
     REFERENCES event(id) ON DELETE CASCADE,

   attribute_name_id SMALLINT NOT NULL,
     CONSTRAINT attribute_fk2
     FOREIGN KEY (attribute_name_id)
     REFERENCES attribute_name(id),

     CONSTRAINT attribute_pk
     PRIMARY KEY(event_id, attribute_name_id),

   -- typical SIP attribute values are <200 chars; cap at 1024 to keep
   -- rows in-page rather than off-page (TEXT) for the hot table
   value VARCHAR(1024) NOT NULL
);


-- ─────────────────────────────────────────────────────────────────────────
-- Time-based partitioning (operator-enabled when retention policy is set)
-- ─────────────────────────────────────────────────────────────────────────
--
-- MySQL InnoDB requires the partitioning column to appear in every UNIQUE
-- index, including the PRIMARY KEY. To enable RANGE partitioning by
-- `created`, change the event PK to a composite and re-create:
--
--   ALTER TABLE event
--     DROP PRIMARY KEY,
--     ADD PRIMARY KEY (id, created),
--     PARTITION BY RANGE (TO_DAYS(created)) (
--       PARTITION p_2026 VALUES LESS THAN (TO_DAYS('2027-01-01')),
--       PARTITION p_2027 VALUES LESS THAN (TO_DAYS('2028-01-01')),
--       PARTITION p_2028 VALUES LESS THAN (TO_DAYS('2029-01-01')),
--       PARTITION p_future VALUES LESS THAN MAXVALUE
--     );
--
-- Annual retention drop:
--
--   ALTER TABLE event DROP PARTITION p_2026;
--
-- The `attribute` table cannot be cleanly partitioned alongside `event`
-- because foreign keys are not supported between partitioned tables in
-- all MySQL versions. Two operational options:
--   (a) coordinated retention: drop event partition, then manually
--       DELETE orphaned attributes (slow but works);
--   (b) drop the FK constraint on attribute.event_id and partition both
--       by RANGE on event_id (faster ops, weaker referential integrity).
-- Pick (b) if retention churn becomes operationally painful.
