-- BLADE Analytics schema — Oracle (12c+).
--
-- Generated from MySQL-database-schema.sql (the single source of truth).
--
-- Oracle dialect notes:
--   * Types: BIGINT -> NUMBER(19); SMALLINT -> NUMBER(5); VARCHAR(n) ->
--     VARCHAR2(n CHAR); TEXT -> CLOB; DATETIME/TIMESTAMP -> TIMESTAMP;
--     DEFAULT CURRENT_TIMESTAMP -> DEFAULT SYSTIMESTAMP.
--   * AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY (12c+). On 11g, replace
--     each identity column with a SEQUENCE + a BEFORE-INSERT trigger.
--   * Table names are plural; this also sidesteps `SESSION` being a reserved
--     word in Oracle (the singular `session` would have to be quoted).
--   * "One open session per correlator" uses a function-based unique index
--     (closed rows index to an all-NULL key, which Oracle does not store, so only
--     open rows are checked) in place of MySQL's VIRTUAL generated open_key.
--   * There is no DROP TABLE IF EXISTS — the PL/SQL block drops each table if
--     present. An Oracle schema is a DBA-provisioned user; run as that user.

-- Drop existing objects (ignores anything not present).
BEGIN
   FOR t IN (SELECT table_name FROM user_tables
             WHERE table_name IN
               ('ATTRIBUTES','ATTRIBUTE_NAMES','EVENTS','EVENT_TYPES',
                'SESSION_KEYS','SESSIONS','APPLICATIONS')) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- application instances — unique deployments in time
CREATE TABLE applications(
   id        NUMBER(19)        NOT NULL,   -- producer-generated random 64-bit
   CONSTRAINT application_pk PRIMARY KEY(id),
   name      VARCHAR2(32 CHAR) NOT NULL,
   version   VARCHAR2(16 CHAR),
   host      VARCHAR2(128 CHAR),
   domain    VARCHAR2(64 CHAR),            -- weblogic cluster domain; not DNS
   server    VARCHAR2(64 CHAR),            -- weblogic server name; not hostname
   tenant    VARCHAR2(64 CHAR),            -- customer code for multi-tenant RLS; NULL = single-tenant
   created   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
   destroyed TIMESTAMP,
   comments  CLOB
);

-- tenant discriminator: session/event rows reach their tenant via application_id
CREATE INDEX idx_application_tenant ON applications(tenant);

CREATE TABLE sessions(
   id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,  -- DB-assigned key
   CONSTRAINT session_pk PRIMARY KEY(id),

   application_id NUMBER(19) NOT NULL,
   CONSTRAINT session_fk1 FOREIGN KEY (application_id)
      REFERENCES applications(id) ON DELETE CASCADE,

   -- cluster_name is the hosting-environment id (AnalyticsConfig.domainId),
   -- stamped by the analytics server; vorpal_id is the call's X-Vorpal-ID.
   -- Together they keep a call unique when several environments share one DB.
   cluster_name VARCHAR2(64 CHAR) NOT NULL,
   vorpal_id    NUMBER(19)        NOT NULL,

   created   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,  -- real call-start time
   destroyed TIMESTAMP                                 -- NULL while open
);

CREATE INDEX idx_session_correlator ON sessions(cluster_name, vorpal_id, destroyed);
CREATE INDEX idx_session_created     ON sessions(created);
CREATE INDEX idx_session_app_created ON sessions(application_id, created);

-- one OPEN session per correlator (function-based: closed rows -> all-NULL key,
-- not stored by Oracle, so only open rows participate in the uniqueness check)
CREATE UNIQUE INDEX session_open_uk ON sessions(
   CASE WHEN destroyed IS NULL THEN cluster_name END,
   CASE WHEN destroyed IS NULL THEN vorpal_id    END);

-- index keys referencing a session (selectors, e.g. 'Cisco-Gucid' or 'caller')
CREATE TABLE session_keys(
   session_id NUMBER(19)         NOT NULL,
   CONSTRAINT session_key_fk1 FOREIGN KEY (session_id)
      REFERENCES sessions(id) ON DELETE CASCADE,
   name       VARCHAR2(64 CHAR)  NOT NULL,
   value      VARCHAR2(128 CHAR) NOT NULL,
   CONSTRAINT session_key_pk PRIMARY KEY(session_id, name, value)
);
CREATE INDEX idx_session_key_lookup ON session_keys(name, value);

-- normalized event-name lookup; populated lazily by the consumer
CREATE TABLE event_types(
   id   NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
   CONSTRAINT event_type_pk PRIMARY KEY(id),
   name VARCHAR2(64 CHAR) NOT NULL,
   CONSTRAINT event_type_uk UNIQUE (name)
);

-- events associated with a session (and/or application for sessionless events)
CREATE TABLE events(
   id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
   CONSTRAINT event_pk PRIMARY KEY(id),

   application_id NUMBER(19) NOT NULL,
   CONSTRAINT event_fk1 FOREIGN KEY (application_id)
      REFERENCES applications(id),                -- plain FK (no cascade)

   session_id     NUMBER(19),                     -- null for sessionless events
   CONSTRAINT event_fk2 FOREIGN KEY (session_id)
      REFERENCES sessions(id) ON DELETE CASCADE,

   event_type_id  NUMBER(5) NOT NULL,
   CONSTRAINT event_fk3 FOREIGN KEY (event_type_id)
      REFERENCES event_types(id),

   created        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_event_session      ON events(session_id, created);
CREATE INDEX idx_event_type_created ON events(event_type_id, created);
CREATE INDEX idx_event_created      ON events(created);

-- normalized attribute-name lookup; populated lazily by the consumer
CREATE TABLE attribute_names(
   id   NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
   CONSTRAINT attribute_name_pk PRIMARY KEY(id),
   name VARCHAR2(64 CHAR) NOT NULL,
   CONSTRAINT attribute_name_uk UNIQUE (name)
);

-- key/value attributes attached to an event
CREATE TABLE attributes(
   event_id          NUMBER(19) NOT NULL,
   CONSTRAINT attribute_fk1 FOREIGN KEY (event_id)
      REFERENCES events(id) ON DELETE CASCADE,
   attribute_name_id NUMBER(5)  NOT NULL,
   CONSTRAINT attribute_fk2 FOREIGN KEY (attribute_name_id)
      REFERENCES attribute_names(id),
   CONSTRAINT attribute_pk PRIMARY KEY(event_id, attribute_name_id),
   value             VARCHAR2(1024 CHAR) NOT NULL
);

-- Retention: time-based DELETE by `created`, or interval/range partitioning of
-- `events` on `created` (Enterprise Edition). No cascade is relied on for cleanup.
