package org.vorpal.blade.events;

import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import java.io.Serializable;
import java.time.Instant;
import java.util.List;

/// The transfer was refused: either the target's leg returned a failure response, or the REFER
/// itself was refused. Both land here, so this means the transfer did not happen — not specifically
/// that the target said no.
///
/// Generated by the BLADE Event Bus designer — the payload of event type
/// `org.vorpal.blade.transfer.declined`.
///
/// Regenerate rather than hand-edit: this class is derived from the
/// event catalog, and the catalog is what the publisher, the consumer's
/// selector and the ingress validation all agree on.
public class TransferDeclined implements Serializable {

	private static final long serialVersionUID = 1L;

	private String vorpalId;
	private Instant startedAt;
	private Instant occurredAt;
	private String appName;
	private String domain;
	private String server;
	private Instant appStartedAt;
	private List<Attributes> attributes;

	/// The shape of `attributes`.
	public static class Attributes implements Serializable {

		private static final long serialVersionUID = 1L;

		private String name;
		private String value;

		/// Attribute name.
		@JsonPropertyDescription("Attribute name.")
		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		/// Attribute value.
		@JsonPropertyDescription("Attribute value.")
		public String getValue() {
			return value;
		}

		public void setValue(String value) {
			this.value = value;
		}

	}

	/// The Vorpal-ID as it appears on the SIP wire — the correlator shared by every app handling this call.
	@JsonPropertyDescription("The Vorpal-ID as it appears on the SIP wire — the correlator shared by every app handling this call.")
	public String getVorpalId() {
		return vorpalId;
	}

	public void setVorpalId(String vorpalId) {
		this.vorpalId = vorpalId;
	}

	/// When the Vorpal-ID was created, i.e. when the call began. Not the time of this event — that is the envelope's 'time'. Together with vorpalId it identifies the call durably, because Vorpal-IDs are only unique among live sessions and are reused.
	@JsonPropertyDescription("When the Vorpal-ID was created, i.e. when the call began. Not the time of this event — that is the envelope's 'time'. Together with vorpalId it identifies the call durably, because Vorpal-IDs are only unique among live sessions and are reused.")
	public Instant getStartedAt() {
		return startedAt;
	}

	public void setStartedAt(Instant startedAt) {
		this.startedAt = startedAt;
	}

	/// When the event happened, as distinct from when it was published.
	@JsonPropertyDescription("When the event happened, as distinct from when it was published.")
	public Instant getOccurredAt() {
		return occurredAt;
	}

	public void setOccurredAt(Instant occurredAt) {
		this.occurredAt = occurredAt;
	}

	/// The deployed application name.
	@JsonPropertyDescription("The deployed application name.")
	public String getAppName() {
		return appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	/// The WebLogic domain.
	@JsonPropertyDescription("The WebLogic domain.")
	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	/// The server this instance runs on.
	@JsonPropertyDescription("The server this instance runs on.")
	public String getServer() {
		return server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	/// When this application instance started. An instance is one app, on one server, with one configuration — a restart is a new instance, deliberately.
	@JsonPropertyDescription("When this application instance started. An instance is one app, on one server, with one configuration — a restart is a new instance, deliberately.")
	public Instant getAppStartedAt() {
		return appStartedAt;
	}

	public void setAppStartedAt(Instant appStartedAt) {
		this.appStartedAt = appStartedAt;
	}

	/// The attributes this application's configuration extracted from the SIP message. An array of name/value pairs rather than a free-form object, because the field model has no map kind — a map could not be declared, validated or generated from. Names must be unique; the consumer takes the last of any duplicate.
	@JsonPropertyDescription("The attributes this application's configuration extracted from the SIP message. An array of name/value pairs rather than a free-form object, because the field model has no map kind — a map could not be declared, validated or generated from. Names must be unique; the consumer takes the last of any duplicate.")
	public List<Attributes> getAttributes() {
		return attributes;
	}

	public void setAttributes(List<Attributes> attributes) {
		this.attributes = attributes;
	}

}
