package org.vorpal.blade.services.events;


import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.vorpal.blade.framework.v3.events.CloudEvent;
import org.vorpal.blade.framework.v3.events.EventSubscriber;

import com.fasterxml.jackson.databind.ObjectMapper;

/// The `calendar` subscription.
///
/// Creates the appointment when the attendant confirms a meeting.
///
/// Generated by the BLADE Event Bus designer. Fill in the handler bodies
/// below; everything above them is already wired.
///
/// **This file belongs in the consuming application's own source tree.**
/// The framework jar ships inside every BLADE WAR and EJB annotation
/// scanning covers `WEB-INF/lib`, so a consumer placed there would activate
/// in every deployed application at once, all of them contending for one
/// client id.
///
/// Handles:
///  - `net.vorpal.attendant.meeting.scheduled` — Meeting Scheduled
///
/// The selector is derived from those types rather than typed by a human,
/// so it cannot drift from what the publisher actually stamps — a mistyped
/// selector is a silent no-op that looks exactly like "no events yet".
///
/// A **durable** subscription means an event is held while this app is
/// down rather than missed. `One-Copy-Per-Application` makes the whole
/// cluster one logical subscriber, so the event is handled once
/// cluster-wide and not once per engine node.
///
/// It also means **redelivery is routine**, not an edge case: a rolling
/// restart, a failover or a rollback all replay. A redelivered fact is
/// harmless; a redelivered *action* is not. The event carries no delivery
/// contract, so idempotency is this consumer's job — see `firstSight`.
@javax.servlet.annotation.WebListener
public class CalendarEventListener
		implements EventSubscriber.Handler, javax.servlet.ServletContextListener {

	private static final Logger logger = Logger.getLogger(CalendarEventListener.class.getName());
	private static final ObjectMapper MAPPER = new ObjectMapper();

	/// How many recently-seen CloudEvent ids to remember.
	private static final int RECENT_IDS = 4096;

	private static final Map<String, Boolean> RECENT = Collections.synchronizedMap(
			new LinkedHashMap<String, Boolean>(512, 0.75f, false) {
				private static final long serialVersionUID = 1L;

				@Override
				protected boolean removeEldestEntry(Map.Entry<String, Boolean> eldest) {
					return size() > RECENT_IDS;
				}
			});

	/// True the first time this node sees an event id.
	///
	/// **A cheap first filter, not an exactly-once guarantee.** It is per-JVM
	/// and it forgets: it catches the ordinary redelivery — the same event
	/// arriving again within the last few thousand messages on this node — and
	/// nothing beyond that. If repeating this consumer's action is expensive or
	/// wrong, dedupe against whatever durable state the action already writes
	/// (a row, a flag, a session attribute) and treat this as the fast path.
	///
	/// An event with no id is treated as new rather than dropped: losing a
	/// real event is worse than acting twice on a malformed one.
	private static boolean firstSight(String id) {
		return id == null || RECENT.put(id, Boolean.TRUE) == null;
	}

	/// The types this consumer was generated for. Used when the catalog has
	/// nothing to say about this subscription — a fresh domain, or one whose
	/// operator has not touched it.
	public static final java.util.List<String> TYPES =
			java.util.Collections.singletonList("net.vorpal.attendant.meeting.scheduled");

	/// The subscription's name. This SUBSCRIBER's name, never an event type's:
	/// two applications consuming the same event MUST differ here, or they
	/// share one subscription and compete for messages instead of each getting
	/// a copy.
	public static final String SUBSCRIPTION = "calendar";

	/// Keeps the live subscription matching the catalog for as long as this
	/// application is deployed.
	///
	/// **The consumer is its own lifecycle.** It was an `@MessageDriven` class,
	/// where the container owned activation and the selector was a compile-time
	/// constant — so changing which events this application woke for meant
	/// regenerating and redeploying it. Owning the subscription here is what
	/// makes that an operator's edit instead.
	private org.vorpal.blade.framework.v3.events.SubscriptionRegistrar registrar;

	/// This application's event-bus control surface: what it is doing, and a
	/// self-test that publishes one event and waits for it to come back.
	private org.vorpal.blade.framework.v3.events.EventBusControl control;

	@Override
	public void contextInitialized(javax.servlet.ServletContextEvent event) {
		registrar = org.vorpal.blade.framework.v3.events.SubscriptionRegistrar.start(
				event.getServletContext(), SUBSCRIPTION, TYPES, this);
		// deriveName, not getServletContextName: it is the derivation log files
		// and config MBeans already use — documented as needing to agree
		// byte-for-byte — and it cannot come back null.
		control = org.vorpal.blade.framework.v3.events.EventBusControl.register(
				org.vorpal.blade.framework.v2.config.SettingsManager.deriveName(
						event.getServletContext()));
	}

	@Override
	public void contextDestroyed(javax.servlet.ServletContextEvent event) {
		if (registrar != null) {
			registrar.stop();
		}
		if (control != null) {
			control.unregister();
		}
	}

	@Override
	public void handle(java.util.List<CloudEvent> batch) throws Exception {
		for (CloudEvent event : batch) {
			handle(event);
		}
	}

	private void handle(CloudEvent event) {
		try {
			if (!firstSight(event.getId())) {
				logger.fine("already handled " + event.getId());
				return;
			}

			switch (String.valueOf(event.getType())) {
			case "net.vorpal.attendant.meeting.scheduled":
				onMeetingScheduled(event, MAPPER.treeToValue(event.getData(), MeetingScheduled.class));
				break;
			default:
				// The broker filters to exactly the types above, so reaching here
				// means the selector and this switch disagree: regenerate.
				logger.warning("unexpected type " + event.getType()
						+ " — selector and handler disagree; regenerate this consumer");
				break;
			}
		} catch (Exception e) {
			// Swallowed rather than rethrown, and the distinction now matters:
			// throwing would roll the batch back and the broker would redeliver
			// it until the redelivery limit moved it to the error destination.
			// That is right for a failure that might succeed next time; a
			// payload this consumer cannot parse is not one of those.
			logger.log(Level.SEVERE, "failed to handle an event on calendar", e);
		}
	}

	/// The attendant confirmed a meeting with the caller. A calendar app subscribes to this and
	/// creates the appointment.
	///
	/// `net.vorpal.attendant.meeting.scheduled`
	private void onMeetingScheduled(CloudEvent event, MeetingScheduled payload) {
		// A real integration writes an iCalendar entry or calls a partner
		// calendar API here. What matters for the reference is what is already
		// true above this line: this application received its own copy of an
		// event another application published, without either knowing the other
		// exists, and it will not act on it twice if the bus redelivers.
		StringBuilder appointment = new StringBuilder("would create an appointment");
		if (payload.getWho() != null) {
			appointment.append(" with ").append(payload.getWho());
		}
		if (payload.getWhenText() != null) {
			appointment.append(" at ").append(payload.getWhenText());
		}
		if (payload.getLocation() != null) {
			appointment.append(" in ").append(payload.getLocation());
		}
		logger.info(appointment + " [id=" + event.getId() + ", subject=" + event.getSubject() + "]");
	}
}
