package org.vorpal.blade.services.events;

import javax.ejb.ActivationConfigProperty;
import javax.ejb.MessageDriven;
import javax.ejb.TransactionManagement;
import javax.ejb.TransactionManagementType;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.TextMessage;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.vorpal.blade.framework.v3.events.CloudEvent;

import com.fasterxml.jackson.databind.ObjectMapper;

/// The `calendar` subscription.
///
/// Creates the appointment when the attendant confirms a meeting.
///
/// Generated by the BLADE Event Bus designer. Fill in the handler bodies
/// below; everything above them is already wired.
///
/// **This file belongs in the consuming application's own source tree.**
/// The framework jar ships inside every BLADE WAR and EJB annotation
/// scanning covers `WEB-INF/lib`, so a consumer placed there would activate
/// in every deployed application at once, all of them contending for one
/// client id.
///
/// Handles:
///  - `net.vorpal.attendant.meeting.scheduled` — Meeting Scheduled
///
/// The selector is derived from those types rather than typed by a human,
/// so it cannot drift from what the publisher actually stamps — a mistyped
/// selector is a silent no-op that looks exactly like "no events yet".
///
/// A **durable** subscription means an event is held while this app is
/// down rather than missed. `One-Copy-Per-Application` makes the whole
/// cluster one logical subscriber, so the event is handled once
/// cluster-wide and not once per engine node.
///
/// It also means **redelivery is routine**, not an edge case: a rolling
/// restart, a failover or a rollback all replay. A redelivered fact is
/// harmless; a redelivered *action* is not. The event carries no delivery
/// contract, so idempotency is this consumer's job — see `firstSight`.
@TransactionManagement(TransactionManagementType.BEAN)
@MessageDriven(mappedName = "jms/BladeEventBusTopic", activationConfig = {
		@ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Topic"),
		// Named explicitly. Left out, the container falls back to a default
		// connection factory — which works, and quietly means the factory the
		// bus provisions (and its prefetch settings) applies to nothing.
		@ActivationConfigProperty(propertyName = "connectionFactoryJndiName", propertyValue = "jms/BladeEventBusConnectionFactory"),
		@ActivationConfigProperty(propertyName = "subscriptionDurability", propertyValue = "Durable"),
		// Both of these are the SUBSCRIPTION's name, never an event type's. Two
		// applications consuming the same event MUST differ here, or they share
		// one subscription and compete for messages instead of each getting a copy.
		@ActivationConfigProperty(propertyName = "subscriptionName", propertyValue = "calendar"),
		@ActivationConfigProperty(propertyName = "clientId", propertyValue = "calendar"),
		@ActivationConfigProperty(propertyName = "topicMessagesDistributionMode", propertyValue = "One-Copy-Per-Application"),
		@ActivationConfigProperty(propertyName = "distributedDestinationConnection", propertyValue = "EveryMember"),
		// Selector derived from the 1 type this subscription declares. The broker filters, so this app
		// never wakes for an event it would ignore.
		@ActivationConfigProperty(propertyName = "messageSelector", propertyValue = "eventType IN ('net.vorpal.attendant.meeting.scheduled')"),
		@ActivationConfigProperty(propertyName = "acknowledgeMode", propertyValue = "Auto-acknowledge") })
public class CalendarEventListener implements MessageListener {

	private static final Logger logger = Logger.getLogger(CalendarEventListener.class.getName());
	private static final ObjectMapper MAPPER = new ObjectMapper();

	/// How many recently-seen CloudEvent ids to remember.
	private static final int RECENT_IDS = 4096;

	private static final Map<String, Boolean> RECENT = Collections.synchronizedMap(
			new LinkedHashMap<String, Boolean>(512, 0.75f, false) {
				private static final long serialVersionUID = 1L;

				@Override
				protected boolean removeEldestEntry(Map.Entry<String, Boolean> eldest) {
					return size() > RECENT_IDS;
				}
			});

	/// True the first time this node sees an event id.
	///
	/// **A cheap first filter, not an exactly-once guarantee.** It is per-JVM
	/// and it forgets: it catches the ordinary redelivery — the same event
	/// arriving again within the last few thousand messages on this node — and
	/// nothing beyond that. If repeating this consumer's action is expensive or
	/// wrong, dedupe against whatever durable state the action already writes
	/// (a row, a flag, a session attribute) and treat this as the fast path.
	///
	/// An event with no id is treated as new rather than dropped: losing a
	/// real event is worse than acting twice on a malformed one.
	private static boolean firstSight(String id) {
		return id == null || RECENT.put(id, Boolean.TRUE) == null;
	}

	@Override
	public void onMessage(Message message) {
		if (!(message instanceof TextMessage)) {
			logger.warning("ignoring non-TextMessage " + message.getClass().getName());
			return;
		}

		try {
			CloudEvent event = CloudEvent.fromJson(((TextMessage) message).getText());

			if (!firstSight(event.getId())) {
				logger.fine("already handled " + event.getId());
				return;
			}

			switch (String.valueOf(event.getType())) {
			case "net.vorpal.attendant.meeting.scheduled":
				onMeetingScheduled(event, MAPPER.treeToValue(event.getData(), MeetingScheduled.class));
				break;
			default:
				// The broker filters to exactly the types above, so reaching here
				// means the selector and this switch disagree: regenerate.
				logger.warning("unexpected type " + event.getType()
						+ " — selector and handler disagree; regenerate this consumer");
				break;
			}
		} catch (Exception e) {
			// Consume rather than force redelivery: a malformed payload will
			// not fix itself on retry.
			logger.log(Level.SEVERE, "failed to handle an event on calendar", e);
		}
	}

	/// The attendant confirmed a meeting with the caller. A calendar app subscribes to this and
	/// creates the appointment.
	///
	/// `net.vorpal.attendant.meeting.scheduled`
	private void onMeetingScheduled(CloudEvent event, MeetingScheduled payload) {
		// A real integration writes an iCalendar entry or calls a partner
		// calendar API here. What matters for the reference is what is already
		// true above this line: this application received its own copy of an
		// event another application published, without either knowing the other
		// exists, and it will not act on it twice if the bus redelivers.
		StringBuilder appointment = new StringBuilder("would create an appointment");
		if (payload.getWho() != null) {
			appointment.append(" with ").append(payload.getWho());
		}
		if (payload.getWhenText() != null) {
			appointment.append(" at ").append(payload.getWhenText());
		}
		if (payload.getLocation() != null) {
			appointment.append(" in ").append(payload.getLocation());
		}
		logger.info(appointment + " [id=" + event.getId() + ", subject=" + event.getSubject() + "]");
	}
}
