package org.vorpal.blade.services.events;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import java.io.Serializable;

/// The attendant confirmed a meeting with the caller. A calendar app subscribes to this and creates
/// the appointment.
///
/// Generated by the BLADE Event Bus designer — the payload of event type
/// `net.vorpal.attendant.meeting.scheduled`.
///
/// Regenerate rather than hand-edit: this class is derived from the
/// event catalog, and the catalog is what the publisher, the consumer's
/// selector and the ingress validation all agree on.
public class MeetingScheduled implements Serializable {

	private static final long serialVersionUID = 1L;

	private String who;
	private String whenText;
	private String location;

	/// Who the meeting is with, as the caller named them.
	@JsonPropertyDescription("Who the meeting is with, as the caller named them.")
	public String getWho() {
		return who;
	}

	public void setWho(String who) {
		this.who = who;
	}

	/// When the meeting is, in the caller's own words.
	@JsonProperty("when_text")
	@JsonPropertyDescription("When the meeting is, in the caller's own words.")
	public String getWhenText() {
		return whenText;
	}

	public void setWhenText(String whenText) {
		this.whenText = whenText;
	}

	/// Where, if the caller said.
	@JsonPropertyDescription("Where, if the caller said.")
	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
