package org.vorpal.blade.services.transfer.events;

import javax.ejb.ActivationConfigProperty;
import javax.ejb.MessageDriven;
import javax.ejb.TransactionManagement;
import javax.ejb.TransactionManagementType;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.TextMessage;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.vorpal.blade.framework.v3.events.CloudEvent;
import org.vorpal.blade.events.TransferAbandoned;
import org.vorpal.blade.events.TransferCompleted;
import org.vorpal.blade.events.TransferDeclined;
import org.vorpal.blade.events.TransferInitiated;
import org.vorpal.blade.events.TransferRequested;

import com.fasterxml.jackson.databind.ObjectMapper;

/// The `transfer` subscription.
///
/// Watches the transfers this domain performs.
///
/// **This is the worked example of two applications receiving one event.** Every
/// event below also reaches `services/analytics`, which subscribes to the whole
/// bus and writes them to its database. Neither application knows the other
/// exists; the producer published once and knows about neither. That works
/// because the two subscriptions carry different identities — `transfer` here,
/// `analytics-db` there — where an earlier design derived both from the *event
/// type* and gave the two apps the same pair. That is not two subscriptions
/// clashing: it is one subscription named twice, and the two apps would have
/// competed for a single stream, each receiving roughly half its events,
/// intermittently, with nothing anywhere reporting it.
///
/// **It observes; it does not act.** A consumer that performed transfers off a
/// bus event would be a real feature with real questions attached — which call,
/// on whose authority, and what happens when a rolling restart replays the
/// event an hour later — and none of those are answered by a worked example.
/// The `firstSight` guard above is what an actor would build on: it is already
/// wired, and it is the reason a redelivered *fact* here is harmless.
///
/// Generated by the BLADE Event Bus designer, then given handler bodies.
///
/// **This file belongs in the consuming application's own source tree.**
/// The framework jar ships inside every BLADE WAR and EJB annotation
/// scanning covers `WEB-INF/lib`, so a consumer placed there would activate
/// in every deployed application at once, all of them contending for one
/// client id.
///
/// Handles:
///  - `net.vorpal.blade.transfer.requested` — Transfer Requested
///  - `net.vorpal.blade.transfer.initiated` — Transfer Initiated
///  - `net.vorpal.blade.transfer.completed` — Transfer Completed
///  - `net.vorpal.blade.transfer.declined` — Transfer Declined
///  - `net.vorpal.blade.transfer.abandoned` — Transfer Abandoned
///
/// The selector is derived from those types rather than typed by a human,
/// so it cannot drift from what the publisher actually stamps — a mistyped
/// selector is a silent no-op that looks exactly like "no events yet".
///
/// A **durable** subscription means an event is held while this app is
/// down rather than missed. `One-Copy-Per-Application` makes the whole
/// cluster one logical subscriber, so the event is handled once
/// cluster-wide and not once per engine node.
///
/// It also means **redelivery is routine**, not an edge case: a rolling
/// restart, a failover or a rollback all replay. A redelivered fact is
/// harmless; a redelivered *action* is not. The event carries no delivery
/// contract, so idempotency is this consumer's job — see `firstSight`.
@TransactionManagement(TransactionManagementType.BEAN)
@MessageDriven(mappedName = "jms/BladeEventBusTopic", activationConfig = {
		@ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Topic"),
		// Named explicitly. Left out, the container falls back to a default
		// connection factory — which works, and quietly means the factory the
		// bus provisions (and its prefetch settings) applies to nothing.
		@ActivationConfigProperty(propertyName = "connectionFactoryJndiName", propertyValue = "jms/BladeEventBusConnectionFactory"),
		@ActivationConfigProperty(propertyName = "subscriptionDurability", propertyValue = "Durable"),
		// Both of these are the SUBSCRIPTION's name, never an event type's. Two
		// applications consuming the same event MUST differ here, or they share
		// one subscription and compete for messages instead of each getting a copy.
		@ActivationConfigProperty(propertyName = "subscriptionName", propertyValue = "transfer"),
		@ActivationConfigProperty(propertyName = "clientId", propertyValue = "transfer"),
		@ActivationConfigProperty(propertyName = "topicMessagesDistributionMode", propertyValue = "One-Copy-Per-Application"),
		@ActivationConfigProperty(propertyName = "distributedDestinationConnection", propertyValue = "EveryMember"),
		// Selector derived from the 5 types this subscription declares. The broker filters, so this app
		// never wakes for an event it would ignore.
		@ActivationConfigProperty(propertyName = "messageSelector", propertyValue = "eventType IN ('net.vorpal.blade.transfer.requested', 'net.vorpal.blade.transfer.initiated', 'net.vorpal.blade.transfer.completed', 'net.vorpal.blade.transfer.declined', 'net.vorpal.blade.transfer.abandoned')"),
		@ActivationConfigProperty(propertyName = "acknowledgeMode", propertyValue = "Auto-acknowledge") })
public class TransferEventListener implements MessageListener {

	private static final Logger logger = Logger.getLogger(TransferEventListener.class.getName());
	private static final ObjectMapper MAPPER = new ObjectMapper();

	/// How many recently-seen CloudEvent ids to remember.
	private static final int RECENT_IDS = 4096;

	private static final Map<String, Boolean> RECENT = Collections.synchronizedMap(
			new LinkedHashMap<String, Boolean>(512, 0.75f, false) {
				private static final long serialVersionUID = 1L;

				@Override
				protected boolean removeEldestEntry(Map.Entry<String, Boolean> eldest) {
					return size() > RECENT_IDS;
				}
			});

	/// True the first time this node sees an event id.
	///
	/// **A cheap first filter, not an exactly-once guarantee.** It is per-JVM
	/// and it forgets: it catches the ordinary redelivery — the same event
	/// arriving again within the last few thousand messages on this node — and
	/// nothing beyond that. If repeating this consumer's action is expensive or
	/// wrong, dedupe against whatever durable state the action already writes
	/// (a row, a flag, a session attribute) and treat this as the fast path.
	///
	/// An event with no id is treated as new rather than dropped: losing a
	/// real event is worse than acting twice on a malformed one.
	private static boolean firstSight(String id) {
		return id == null || RECENT.put(id, Boolean.TRUE) == null;
	}

	@Override
	public void onMessage(Message message) {
		if (!(message instanceof TextMessage)) {
			logger.warning("ignoring non-TextMessage " + message.getClass().getName());
			return;
		}

		try {
			CloudEvent event = CloudEvent.fromJson(((TextMessage) message).getText());

			if (!firstSight(event.getId())) {
				logger.fine("already handled " + event.getId());
				return;
			}

			switch (String.valueOf(event.getType())) {
			case "net.vorpal.blade.transfer.requested":
				onTransferRequested(event, MAPPER.treeToValue(event.getData(), TransferRequested.class));
				break;
			case "net.vorpal.blade.transfer.initiated":
				onTransferInitiated(event, MAPPER.treeToValue(event.getData(), TransferInitiated.class));
				break;
			case "net.vorpal.blade.transfer.completed":
				onTransferCompleted(event, MAPPER.treeToValue(event.getData(), TransferCompleted.class));
				break;
			case "net.vorpal.blade.transfer.declined":
				onTransferDeclined(event, MAPPER.treeToValue(event.getData(), TransferDeclined.class));
				break;
			case "net.vorpal.blade.transfer.abandoned":
				onTransferAbandoned(event, MAPPER.treeToValue(event.getData(), TransferAbandoned.class));
				break;
			default:
				// The broker filters to exactly the types above, so reaching here
				// means the selector and this switch disagree: regenerate.
				logger.warning("unexpected type " + event.getType()
						+ " — selector and handler disagree; regenerate this consumer");
				break;
			}
		} catch (Exception e) {
			// Consume rather than force redelivery: a malformed payload will
			// not fix itself on retry.
			logger.log(Level.SEVERE, "failed to handle an event on transfer", e);
		}
	}

	/// A REFER arrived from the transferor, before anything was done about it. This is a fact, not a
	/// command: it says a REFER was received, not that anyone should transfer. A transfer app
	/// subscribes and performs the transfer; analytics subscribes to the same fact and records it;
	/// neither knows about the other.
	///
	/// `net.vorpal.blade.transfer.requested`
	private void onTransferRequested(CloudEvent event, TransferRequested payload) {
		logger.info(describe("a transfer was asked for", event, payload.getAppName(), payload.getOccurredAt()));
	}

	/// The transfer is under way — a blind transfer sent the INVITE to the target, or a refer transfer
	/// saw a 100 Trying sipfrag come back in a NOTIFY.
	///
	/// `net.vorpal.blade.transfer.initiated`
	private void onTransferInitiated(CloudEvent event, TransferInitiated payload) {
		logger.info(describe("the transfer is under way", event, payload.getAppName(), payload.getOccurredAt()));
	}

	/// The transfer target answered — a success response to the target INVITE, or a 200 OK sipfrag in
	/// a NOTIFY.
	///
	/// `net.vorpal.blade.transfer.completed`
	private void onTransferCompleted(CloudEvent event, TransferCompleted payload) {
		logger.info(describe("the transfer target answered", event, payload.getAppName(), payload.getOccurredAt()));
	}

	/// The transfer was refused: either the target's leg returned a failure response, or the REFER
	/// itself was refused. Both land here, so this means the transfer did not happen — not
	/// specifically that the target said no.
	///
	/// `net.vorpal.blade.transfer.declined`
	private void onTransferDeclined(CloudEvent event, TransferDeclined payload) {
		logger.info(describe("the transfer was refused", event, payload.getAppName(), payload.getOccurredAt()));
	}

	/// The transferee gave up before the transfer completed — a BYE or CANCEL from the transferee, or
	/// a 487 from the target caused by one.
	///
	/// `net.vorpal.blade.transfer.abandoned`
	private void onTransferAbandoned(CloudEvent event, TransferAbandoned payload) {
		logger.info(describe("the transferee gave up", event, payload.getAppName(), payload.getOccurredAt()));
	}

	/// One line per event, saying what happened, to which call, and when.
	///
	/// `subject` is the correlator — the Vorpal-ID and the call's birth instant —
	/// so a line here joins to the same call in the analytics database, which
	/// received its own copy of this event.
	private static String describe(String what, CloudEvent event, String appName, java.time.Instant occurredAt) {
		return what + " [call=" + event.getSubject() + ", app=" + appName + ", at=" + occurredAt + ", id="
				+ event.getId() + "]";
	}
}
