# Production build profile - services only, no test apps
#
# Add modules to include in the build and EAR.
# Use the full project directory name.

# Services
acl
analytics
hold
options
presence
proxy-balancer
proxy-block
proxy-registrar
proxy-router
queue
tpcc
transfer
