-- For MySQL

DROP TABLE IF EXISTS attribute;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS session_key;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS application;

-- this table tracks application instances, unique deployments in time
CREATE TABLE application(
   -- generated by a Java hash algorithm; not guaranteed to be unique
   -- odds of collision are ~0.023% over a 20-year period
   id INTEGER NOT NULL,
   CONSTRAINT application_pk PRIMARY KEY(id),

   -- application name, like 'transfer' (without version number)
   name VARCHAR(32) NOT NULL,

   -- application version, like '1.0.1'
   version VARCHAR(16) DEFAULT NULL,

   -- hostname of the machine, like engine1.replicated.vorpal.org
   host VARCHAR(256) DEFAULT NULL,

   -- weblogic cluster domain, like 'replicated'; not related to DNS
   domain VARCHAR(64) DEFAULT NULL,

   -- weblogic server name, like 'engine1'; not related to hostname
   server VARCHAR(64) DEFAULT NULL,

   -- instant the application started
   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

   -- instant the application stopped (NULL while running)
   destroyed TIMESTAMP NULL DEFAULT NULL,

   -- additional user-defined data, like hardware specs (JSON format)
   comments TEXT NULL,

   -- in the unlikely event of a collision, comments will be appended here.
   -- this will help identify if a different app triggered an event
   collisions TEXT NULL
);

CREATE TABLE session(
    -- auto-incremented primary key
    id BIGINT NOT NULL AUTO_INCREMENT,
    CONSTRAINT session_pk
    PRIMARY KEY(id),

    -- the application that created this session
    application_id INTEGER NOT NULL,
    CONSTRAINT session_fk1 FOREIGN KEY (application_id)
    REFERENCES application(id) ON DELETE CASCADE,

    -- instant it was first generated
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_session_created (created),

    -- instant it was destroyed (NULL while active)
    destroyed TIMESTAMP NULL DEFAULT NULL
);

-- this table maintains a list of index keys referencing a session;
-- there may be multiple sessions, depending on the uniqueness of the value
CREATE TABLE session_key(
    -- the matching session
    session_id BIGINT NOT NULL,
      CONSTRAINT session_key_fk1 FOREIGN KEY (session_id)
      REFERENCES session(id) ON DELETE CASCADE,

    -- name of the 'selector', something like 'Cisco-Gucid' or 'caller'
    name VARCHAR(64) NOT NULL,

    -- value of the 'selector', may not be unique
    value VARCHAR(256) NOT NULL,
    
      CONSTRAINT session_key_pk
      PRIMARY KEY(session_id, name, value),

    -- index for lookups by selector name/value
    INDEX idx_session_key_lookup (name, value)
);

-- this table tracks events associated with a session
CREATE TABLE event(

   -- auto-incremented primary key
   id BIGINT NOT NULL AUTO_INCREMENT,
     CONSTRAINT event_pk
     PRIMARY KEY(id),

   -- all events originate from an application instance
   application_id INTEGER NOT NULL,
     CONSTRAINT event_fk1
     FOREIGN KEY (application_id)
     REFERENCES application(id) ON DELETE CASCADE,

   -- may be null for sessionless events like startup & shutdown
   session_id BIGINT,
     CONSTRAINT event_fk2
     FOREIGN KEY (session_id)
     REFERENCES session(id) ON DELETE CASCADE,

   -- type of event (like 'callStarted')
   name VARCHAR(64) NOT NULL,

   -- timestamp of event
   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

   -- indexes for common queries
   INDEX idx_event_session (session_id, created),
   INDEX idx_event_name (name),
   INDEX idx_event_created (created)
);

-- this table contains a set of attributes related to an event
CREATE TABLE attribute(
   -- from the event table
   event_id BIGINT NOT NULL,
     CONSTRAINT attribute_fk1
     FOREIGN KEY (event_id)
     REFERENCES event(id) ON DELETE CASCADE,

   -- something like 'To' or 'From'
   name VARCHAR(64) NOT NULL,
     CONSTRAINT attribute_pk
     PRIMARY KEY(event_id, name),

   -- something like 'sip:alice@vorpal.org'
   value TEXT NOT NULL
);
